apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: nginx-unprivileged
spec:
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: quay.io/nginx/nginx-unprivileged:latest
    importPolicy:
      scheduled: true
