site_name: OpenShift Training
copyright: Copyright &copy; Oriana Schwickrath 2025
site_url: https://trainings.com
theme:
  name: material
  favicon: docs/assets/images/OpenShift_Logo.png
  icon: 
      admonition:
        note: octicons/tag-16
  features:
    - content.code.copy
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - search.highlight
    - content.code.annotation 
  font:
    text: Merriweather Sans # Google Font (Schriftart
    code: Red Hat Mono # Google Font (Code Schriftart)
  palette: 
    # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep purple
      accent: cyan

    # Palette toggle for dark mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: light green
      accent: teal

nav:
  - "Home": index.md
  - "Use Case": UseCase.md
  - "Session 1": Session1.md

markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.mark
  - admonition
  - pymdownx.details
  - pymdownx.superfences


extra: 
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/oriana-schwickrath-03a906200/
