kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: BUILDCONFIG-NAME
  namespace: NAMESPACE-NAME
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'IMAGESTREAM-NAME:latest'
  resources: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'GIT-REPOSITORY-REFERENCE'
      ref: main
    contextDir: CONTEXT-DIRECTORY
  triggers:
    - type: ConfigChange
  runPolicy: Serial