kind: Service
apiVersion: v1
metadata:
  name: frontend
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: frontend
