apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: frontend
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: "https://github.com/anairo98/openshift-training.git"
      ref: main
    contextDir: "session5_task3/build_directories/frontend"
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: "frontend:latest"
  triggers:
    - type: ConfigChange
    - type: ImageChange
