apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: prometheus
spec:
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: REFERENCE-TO-IMAGE (search for it on the Quay.io website, which is linked in the instructions)
    importPolicy:
      scheduled: true