---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
  labels:
    app: recommendationservice
spec:
  type: ClusterIP
  selector:
    app: recommendation
  ports:
  - name: grpc
    port: 8181
    targetPort: 8181