---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend
spec:
  to:
    kind: Service
    name: frontend
  port:
    targetPort: http
  tls: # Activate Secure Route (Https)
    termination: edge # (TLS- Encyrption ends on the edge of the cluster - Openshift-Router - Router encrypts and traffic gets encrypted forwarded to internal pods)
    insecureEdgeTerminationPolicy: Redirect # Http traffic gets forwarded to https)