apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: database
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: "https://github.com/anairo98/openshift-training.git"
      ref: main
    contextDir: "session5/build_directories/database"
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: "database:latest"
  triggers:
    - type: ConfigChange
    - type: ImageChange
