apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  strategy: {}
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        app: database
    spec:
      containers:
        - image: REFERENCE-TO-IMAGESTREAM:TAG
          name: mariadb
          resources: {}
          #volumeMounts:
          #  - name: databasefolder
          #    mountPath: /var/lib/mysql/data
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 10
            periodSeconds: 5
          startupProbe:
            exec:
              command:
              - bash
              - -c
              - mysql -u ${MYSQL_USER} -p${MYSQL_PASSWORD} -e "SELECT 1"
            periodSeconds: 10
            failureThreshold: 60
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: wealthapp
                  key: DB_USERNAME
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wealthapp
                  key: DB_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: wealthapp
                  key: DB_DATABASE
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wealthapp
                  key: DB_PASSWORD
