apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/3-tier-example/httpd-cgi:2.4
          name: httpd-cgi
          resources: {}
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 10
          volumeMounts:
            - name: api-config
              mountPath: /var/www/cgi-bin/data.py
              subPath: data.py
            - name: api-config
              mountPath: /etc/httpd/conf.d/cgi.conf
              subPath: cgi.conf
            - name: api-config
              mountPath: /etc/httpd/conf.d/cgi-default-data.conf
              subPath: cgi-default-data.conf
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: 3tier-app
                  key: DB_HOST
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: 3tier-app
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: 3tier-app
                  key: DB_PASSWORD
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: 3tier-app
                  key: DB_DATABASE
        - name: busybox
          image: 'docker.io/radial/busyboxplus@sha256:f26b8738e52cd1dba801eb1978804e663c48e1e9cff128ac9423218be83c55b8'
          command:
            - sh
            - '-c'
            - while true ; do echo "still running" ; sleep 5 ; done
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      volumes:
        - name: api-config
          configMap:
            name: 3tier-app
            defaultMode: 360
#  triggers:
#    - type: ConfigChange
#    - type: ImageChange
#      imageChangeParams:
#        automatic: true
#        containerNames:
#          - httpd-cgi
#        from:
#          kind: ImageStreamTag
#          name: httpd-cgi:2.4
#          namespace: 3-tier-example
  strategy:
    type: RollingUpdate
status: {}
