apiVersion: v1
data:
  API_HOST: backend
  API_PORT: "8080"
  DB_HOST: database
  app.py: |
    #!/usr/bin/env python3
    import os
    import cgi
    import requests
    import socket

    print("Content-type:text/html\n\n")
    print("<head><title>Customer Database</title></head>\n")
    print("<body>\n")
    print("<h1>Customer Database Access</h1>\n")

    api_host = os.getenv("API_HOST")
    api_port = os.environ["API_PORT"] if "DB_PORT" in os.environ.keys() else "8080"
    #remote = os.getenv("REMOTE_ADDR")
    form = cgi.FieldStorage()
    querystring = form.getvalue("querystring")
    print(querystring)
    print("___")
    #if remote in webservers:
    #    accessName = webservers[remote]
    #else:
    #    accessName = remote
    accessName = socket.gethostname()

    print("Accessed via Pod:", accessName, "\n<p>")

    if querystring != None:
        url = 'http://'+api_host+':'+api_port+'/cgi-bin/data.py?querystring=' + querystring
    else:
        url = 'http://'+api_host+':'+api_port+'/cgi-bin/data.py'
        querystring = ""

    r = requests.get(url)

    print('<form action="/cgi-bin/app.py">')
    print(' Name Filter (blank for all records):')
    print(' <input type="text" name="querystring" value="'+querystring+'">')
    print(' <input type="submit" value="Apply">')
    print('</form>')

    print("\n<table border=1 bordercolor=black cellpadding=5 cellspacing=0>")

    print("\n<th>Rank</th><th>Name</th><th>Universe</th><th>Revenue</th>")

    # deal with the data coming across the wire
    a = r.text.split("|\n#")
    for row in a:
        if len(row) != 1:
            print("<tr>")
            splitrow = row.split("|")
            for item in splitrow:
                if item != None:
                    print("<td>",item,"</td>")
            print("</tr>\n")
        print("</body></html>\n")
  cgi.conf: |
    PassEnv DB_HOST
    PassEnv DB_PORT
    PassEnv DB_USERNAME
    PassEnv DB_PASSWORD
    PassEnv DB_DATABASE
    PassEnv API_HOST
    PassEnv API_PORT
  cgi-default-app.conf: |
    <Directory "/var/www/html">
      Options +ExecCGI
      DirectoryIndex /cgi-bin/app.py
    </Directory>
  cgi-default-data.conf: |
    <Directory "/var/www/html">
      Options +ExecCGI
      DirectoryIndex /cgi-bin/data.py
    </Directory>
  data.py: |
    #!/usr/bin/env python3
    import cgi
    #import sqlite3
    import mysql.connector
    import os

    db = mysql.connector.connect(
        host=os.environ['DB_HOST'],
        user=os.environ['DB_USERNAME'],
        password=os.environ['DB_PASSWORD'],
        database=os.environ['DB_DATABASE']
    )

    #conn = sqlite3.connect('/etc/httpd/db/clients.db')
    curs = db.cursor()
    print("Content-type:text/plain\n\n")
    form = cgi.FieldStorage()
    querystring = form.getvalue("querystring")

    if querystring is not None:
        queryval = "%" + querystring + "%"
        select = "SELECT * FROM clients WHERE name LIKE '" + queryval + "'"
    else:
        select = "SELECT * FROM clients"
    curs.execute(select)
    result = curs.fetchall()
    for row in result:
        if len(row) == 4:
            for item in row:
                print(item,'|')
            print("#")
    db.close()
  init_db.sql: |
    USE 3tier;

    CREATE TABLE clients (
     Rank integer,
     Name varchar(30),
     Universe varchar(55),
     Revenue varchar(20)
     );

     INSERT INTO clients VALUES
     (1,'CHOAM','Dune','$1.7 trillion'),
     (2,'Acme Corp.','Looney Tunes','$348.7 billion'),
     (3,'Sirius Cybernetics Corp.',"Hitchhiker's Guide",'$327.2 billion'),
     (4,'Buy n Large','Wall-E','$291.8 billion'),
     (5,'Aperture Science, Inc.','Valve','$163.4 billion'),
     (6,'SPECTRE','007','$157.1 billion'),
     (7,'Very Big Corp. of America','Monty Python','$146.6 billion'),
     (8,'Frobozz Magic Co.','Zork','$112.9 billion'),
     (9,'Warbucks Industries',"Lil' Orphan Annie",'$61.5 billion'),
     (10,'Tyrell Corp.','Bladerunner','$59.4 billion'),
     (11,'Wayne Enterprises','Batman','$31.3 billion'),
     (12,'Virtucon','Austin Powers','$24.9 billion'),
     (13,'Globex','The Simpsons','$23.7 billion'),
     (14,'Umbrella Corp.','Resident Evil','$22.6 billion'),
     (15,'Wonka Industries','Charlie and the Chocolate Factory','$21.0 billion'),
     (16,'Stark Industries','Iron Man','$20.3 billion'),
     (17,'Clampett Oil','Beverly Hillbillies','$18.1 billion'),
     (18,'Oceanic Airlines','Lost','$7.8 billion'),
     (19,'Brawndo','Idiocracy','$5.8 billion'),
     (20,'Cyberdyne Systems Corp.','Terminator','$5.5 billion'),
     (21,'Paper Street Soap Company','Fight Club','$5.0 billion'),
     (22,'Gringotts','Harry Potter','$4.4 billion'),
     (23,'Oscorp','Spider-Man','$3.1 billion'),
     (24,'Nakatomi Trading Corp.','Die-Hard','$2.5 billion'),
     (25,'Los Pollos Hermanos','Breaking Bad','$1.3 billion');
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: 3tier-app
