apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: REFERENCE-TO-IMAGESTREAM:TAG
          name: httpd-cgi
          resources: {}
          env:
          - name: DB_HOST
            configMapKeyRef:
              name: wealthapp
              key: DB_HOST
          - name: DB_USERNAME
            secretKeyRef:
              name: wealthapp
              key: DB_USERNAME
          - name: DB_PASSWORD
            secretKeyRef:
              name: wealthapp
              key: DB_PASSWORD
          - name: DB_DATABASE
            secretKeyRef:
              name: wealthapp
              key: DB_DATABASE
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 10
  strategy:
    type: RollingUpdate
status: {}
